version: 2
jobs:
  build:
    working_directory: ~/circulate
    docker:
      - image: node:6
      - image: node:7
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm test