version: 2
jobs:
  build:
    working_directory: ~/circulate
    docker:
      - image: livingdocs/nvm
    steps:
      - checkout
      - run:
          name: Initial OS config
          command: export NVM_DIR=/usr/share/nvm
      - run:
          name: Initial OS config
          command: . /usr/share/nvm/nvm.sh
      - run:
          name: Initial OS config
          command: source /usr/share/nvm/nvm.sh
      - run:
          name: Initial OS config
          command: ls /usr/share/nvm
      - run:
          name: Install Node 4,5,6,7
          command: nvm install 4 && nvm install 5 && nvm install 6 && nvm install 7
      - run:
          name: Run on Node 4
          command: nvm use 4 && rm -rf node_modules && npm install && npm test
      - run:
          name: Run on Node 5
          command: nvm use 5 && rm -rf node_modules && npm install && npm test
      - run:
          name: Run on Node 6
          command: nvm use 6 && rm -rf node_modules && npm install && npm test
      - run:
          name: Run on Node 7
          command: nvm use 7 && rm -rf node_modules && npm install && npm test
